export const UI_CHANGE_TITLE = 'UI_CHANGE_TITLE';
export const UI_TOGGLE_FOOTER = 'UI_TOGGLE_FOOTER';
export const UI_TOGGLE_HEADER = 'UI_TOGGLE_HEADER';
export const GET_CHANGE_ROOM= 'GET_CHANGE_ROOM';
export const GET_DETAIL = 'GET_DETAIL';
export const DETAIL_ADD_TO_CART_ASYNC = 'DETAIL_ADD_TO_CART_ASYNC';

export const GET_MALL_LIST = 'GET_MALL_LIST'
export const DETAIL_ADD_TO_CART = 'DETAIL_ADD_TO_CART'


export const CART_DELETE_PROD = 'CART_DELETE_PROD'
